name: Build and Deploy

on:
  push:
    branches: [ main ]

permissions:
  contents: read
  packages: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'

      - name: Install
        run: npm ci

      - name: Build
        run: npm run build

      - name: Extract version & name (node)
        run: |
          VERSION=$(node -p "require('./package.json').version")
          APP_NAME=$(node -p "require('./package.json').name")
          echo "VERSION=$VERSION" >> $GITHUB_ENV
          echo "APP_NAME=$APP_NAME" >> $GITHUB_ENV

      # ---- GHCR login con PAT de escritura ----
      - name: Login GHCR (PAT)
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GHCR_PAT }}

      - name: Build & push image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ghcr.io/${{ github.repository }}:${{ env.VERSION }}

      # ---- SSH known_hosts desde secreto ----
      - name: Write known_hosts
        if: ${{ secrets.SSH_KNOWN_HOSTS != '' }}
        run: |
          mkdir -p ~/.ssh
          chmod 700 ~/.ssh
          echo "${{ secrets.SSH_KNOWN_HOSTS }}" >> ~/.ssh/known_hosts
          chmod 600 ~/.ssh/known_hosts

      - name: SSH smoke test
        uses: appleboy/ssh-action@v1.2.2
        with:
          host: ${{ secrets.SSH_HOST }}
          port: ${{ secrets.SSH_PORT }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            whoami
            hostname
            uptime

      # ---- Deploy en el servidor ----
      - name: Deploy over SSH
        uses: appleboy/ssh-action@v1.2.2
        with:
          host: ${{ secrets.SSH_HOST }}
          port: ${{ secrets.SSH_PORT }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          debug: true
          script: |
            set -euo pipefail
            cd "${{ secrets.PATH_DEPLOYMENTS }}"
            git pull

            # (Opcional) Actualizar tag en docker-compose si detectas versión distinta
            if grep -qE "image:\s*ghcr\.io/asixc/${{ env.APP_NAME }}:" docker-compose.yml; then
              CURRENT_VERSION=$(grep -oP 'image:\s*ghcr\.io/asixc/${{ env.APP_NAME }}:\K[0-9]+\.[0-9]+\.[0-9]+' docker-compose.yml || true)
              if [ "${CURRENT_VERSION:-}" != "${{ env.VERSION }}" ]; then
                sed -i -E "s|(image:\s*ghcr\.io/asixc/${{ env.APP_NAME }}:).*|\1${{ env.VERSION }}|g" docker-compose.yml
                echo "docker-compose.yml actualizado a ${{ env.VERSION }}"
              else
                echo "Version is the same, no need to update."
              fi
            else
              echo "No se encontró la línea de image esperada; no se modifica docker-compose.yml"
            fi

            # Si tu imagen es PRIVADA en GHCR, haz login de solo lectura en el server:
            docker login ghcr.io -u "${{ secrets.GHCR_READ_USER }}" -p "${{ secrets.GHCR_READ_PAT }}"

            docker compose pull kcomemos || true
            docker compose up -d kcomemos
            docker image prune -f