name: Build and Push Docker Image

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 'lts/*'

      - name: Install dependencies
        run: npm install

      - name: Build the project
        run: npm run build

      - name: Extract version from package.json
        id: extract_version
        run: echo "VERSION=$(awk -F '\"' '/\"version\":/ {print $4}' package.json)" >> $GITHUB_ENV

      - name: Extract name from package.json
        id: extract_name
        run: echo "APP_NAME=$(awk -F '\"' '/\"name\":/ {print $4}' package.json)" >> $GITHUB_ENV
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}  # O tu nombre de usuario de GitHub específico
          password: ${{ secrets.GHCR_PAT }}
      
      - name: Show repository and version
        run: echo "Building Docker image for repository $GITHUB_REPOSITORY and version $VERSION"

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ghcr.io/${{ github.repository }}:${{ env.VERSION }}
      
      - name: SSH to server and update docker-compose
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          port: ${{ secrets.SSH_PORT }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          script: |
            cd ${{ secrets.PATH_DEPLOYMENTS }}
            sed -i "s|\(image: ghcr.io/asixc/${{ env.APP_NAME }}:\).*|\1${{ env.VERSION }}|g" docker-compose.yml
            git add docker-compose.yml
            git commit -m "Github action deploy new version"
            git push
            docker rmi ghcr.io/asixc/${{ env.APP_NAME }}:${{ env.VERSION }} -f
            docker-compose up -d --remove-orphans
